{% set name = "htpolynet" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/htpolynet-{{ version }}.tar.gz
  sha256: 36da81f4792dfc24665a36c24ff0145de627f9e614ea4ecdd04424f424868259

build:
  entry_points:
    - htpolynet = HTPolyNet.driver:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - pyyaml >=6
    - requests >=2.28
    - pandas >=2
    - scipy >=1.10
    - parmed >=4
    - networkx >=2.8
    - gputil >=1.4
    - matplotlib-base
    - ambertools

test:
  imports:
    - HTPolyNet
  commands:
    - pip check
    - htpolynet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Automated MD System Builder for Amorphous Network Polymers
  dev_url: https://github.com/AbramsGroup/HTPolyNet
  home: https://github.com/AbramsGroup/HTPolyNet
  doc_url: https://abramsgroup.github.io/HTPolyNet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cameronabrams
