{% set name = "htpolynet" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/htpolynet-{{ version }}.tar.gz
  sha256: b771566f584a1781414d54e53875941a49e57511d9a597adb5de9b2b5fa72b2b

build:
  entry_points:
    - htpolynet = HTPolyNet.driver:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - numpy >=1.24
    - pyyaml >=6
    - requests >=2.28
    - pandas >=2
    - scipy >=1.10
    - parmed >=4
    - networkx >=2.8
    - gputil >=1.4
    - matplotlib-base
    - ambertools

test:
  imports:
    - HTPolyNet
  commands:
    - pip check
    - htpolynet --help
  requires:
    - pip

about:
  summary: Automated MD System Builder for Amorphous Network Polymers
  dev_url: https://github.com/AbramsGroup/HTPolyNet
  home: https://github.com/AbramsGroup/HTPolyNet
  doc_url: https://abramsgroup.github.io/HTPolyNet
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cameronabrams
